<script lang="ts">
import { onMount } from 'svelte';
import { Settings, X, Save, Download, ChevronRight, Volume2, Maximize2, Minimize2 } from 'lucide-svelte';
import { audio, midi, getNoteInScale, SCALES } from '$lib/audio/engine';
import type { AppState, ScaleName, Waveform } from '$lib/types';

const INITIAL_STATE: AppState = { scale: 'PentatonicMinor', rootNote: 48, voicesActive: [true,true,true,false], intervals: [0,2,0,2], waveform: 'sawtooth', gridSteps: 21, motionMode: 'free', bpm: 120, clockSource: 'internal', mpeEnabled: false, midiChannel: 1, touchMode: 'mono', delayEnabled: true, delayMix: 0.5 };
let state: AppState = { ...INITIAL_STATE };
let pointerNotes = new Set<number>(), midiNotes = new Set<number>();
let pointers: Record<number,{x:number;y:number;notes:number[]}> = {};
let midiOutputs:{id:string;name:string|null}[] = []; let selectedMidiOut='';
let isControlsOpen = false, isDesktopLayout = true; let isSurfaceFullscreen = false; let surfaceRef: HTMLDivElement; let appRootRef: HTMLDivElement;
let tickCount = 0; let timer: ReturnType<typeof setInterval> | null = null; let arpIndex=0;

$: activeNotes = new Set([...pointerNotes, ...midiNotes]);
$: allHeldNotes = Array.from(new Set(Object.values(pointers).flatMap((p) => p.notes))).sort((a,b)=>a-b);
$: midi.mpeEnabled = state.mpeEnabled;
$: midi.midiChannel = state.midiChannel;
$: audio.setWaveform(state.waveform);
$: audio.setDelay(state.delayEnabled, state.delayMix);
$: if (selectedMidiOut) midi.setOutput(selectedMidiOut);

const calculateNotes=(x:number,y:number)=>{ const degreeX=Math.floor(x*state.gridSteps), degreeY=Math.floor((1-y)*state.gridSteps); const notes=new Set<number>(); if(state.voicesActive[0])notes.add(getNoteInScale(state.scale,state.rootNote,degreeX+state.intervals[0])); if(state.voicesActive[1])notes.add(getNoteInScale(state.scale,state.rootNote,degreeX+state.intervals[1])); if(state.voicesActive[2])notes.add(getNoteInScale(state.scale,state.rootNote-12,degreeY+state.intervals[2])); if(state.voicesActive[3])notes.add(getNoteInScale(state.scale,state.rootNote-12,degreeY+state.intervals[3])); return Array.from(notes).sort((a,b)=>a-b); };

function syncFree(){ if(state.motionMode!=='free') return; const next = new Set(allHeldNotes); for(const n of pointerNotes) if(!next.has(n)&&!midiNotes.has(n)){audio.stopNote(n);midi.stopNote(n);} for(const n of next) if(!pointerNotes.has(n)&&!midiNotes.has(n)){audio.playNote(n);midi.playNote(n);} pointerNotes = next; }
function stepArp(){ if(state.motionMode!=='arp'||allHeldNotes.length===0) return; const note = allHeldNotes[arpIndex%allHeldNotes.length]; for(const n of pointerNotes) if(!midiNotes.has(n)&&n!==note){audio.stopNote(n);midi.stopNote(n);} if(!midiNotes.has(note)){audio.playNote(note);midi.playNote(note);} pointerNotes=new Set([note]); arpIndex++; }
function resetArpIfEmpty(){ if(state.motionMode==='arp'&&allHeldNotes.length===0){ for(const n of pointerNotes) if(!midiNotes.has(n)){audio.stopNote(n);midi.stopNote(n);} pointerNotes=new Set(); arpIndex=0; } }
$: { syncFree(); resetArpIfEmpty(); }

function setupClock(){ if(timer) clearInterval(timer); midi.onClockTick=null; midi.onStart=null; midi.onStop=null; tickCount=0; if(state.clockSource==='internal'){ const tickMs = 60000/state.bpm/24; timer = setInterval(()=>{ midi.sendClock(); if(tickCount%6===0) stepArp(); tickCount++; }, tickMs); } else { midi.onClockTick=()=>{ if(tickCount%6===0) stepArp(); tickCount++; }; midi.onStart=()=>{tickCount=0; arpIndex=0;}; midi.onStop=()=>{tickCount=0;}; } }
$: if (state.clockSource || state.bpm) setupClock();



async function toggleSurfaceFullscreen(){
	if(!appRootRef) return;
	if(!document.fullscreenElement){
		await appRootRef.requestFullscreen();
		isSurfaceFullscreen = true;
		isControlsOpen = false;
		return;
	}
	await document.exitFullscreen();
}

onMount(() => {
	const onFsChange = () => {
		isSurfaceFullscreen = !!document.fullscreenElement;
	};
	document.addEventListener('fullscreenchange', onFsChange);
	return () => document.removeEventListener('fullscreenchange', onFsChange);
});
function pointerDown(e: PointerEvent){ audio.init(); surfaceRef.setPointerCapture(e.pointerId); const r=surfaceRef.getBoundingClientRect(); const x=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)); const y=Math.max(0,Math.min(1,(e.clientY-r.top)/r.height)); const notes=calculateNotes(x,y); pointers = state.touchMode==='mono' ? {[e.pointerId]:{x,y,notes}} : {...pointers,[e.pointerId]:{x,y,notes}}; }
function pointerMove(e: PointerEvent){ if(!pointers[e.pointerId]) return; const r=surfaceRef.getBoundingClientRect(); const x=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)); const y=Math.max(0,Math.min(1,(e.clientY-r.top)/r.height)); pointers={...pointers,[e.pointerId]:{x,y,notes:calculateNotes(x,y)}}; }
function pointerUp(e: PointerEvent){ const n={...pointers}; delete n[e.pointerId]; pointers=n; if(surfaceRef?.hasPointerCapture(e.pointerId)) surfaceRef.releasePointerCapture(e.pointerId); }

onMount(async()=>{ isDesktopLayout = window.innerWidth >= 1280; const resize=()=>{ isDesktopLayout=window.innerWidth>=1280; if(isDesktopLayout) isControlsOpen=false; }; window.addEventListener('resize',resize); await midi.init(); midiOutputs=midi.getOutputs(); if(midiOutputs[0]) selectedMidiOut=midiOutputs[0].id; midi.onNoteOn=(note,velocity)=>{ audio.init(); audio.playNote(note,velocity); midiNotes = new Set(midiNotes).add(note); }; midi.onNoteOff=(note)=>{ audio.stopNote(note); const n=new Set(midiNotes); n.delete(note); midiNotes=n; }; setupClock(); return ()=>{ window.removeEventListener('resize',resize); if(timer) clearInterval(timer); }; });
</script>

<div bind:this={appRootRef} class="h-dvh min-h-screen bg-[#E4E3E0] text-[#141414] font-mono flex flex-col selection:bg-[#F27D26] selection:text-white overflow-hidden">
<header class="p-3 xl:p-4 border-b border-[#141414] flex justify-between items-center bg-[#E4E3E0] z-30 shrink-0"><div class="flex items-center gap-3 xl:gap-4"><button on:click={() => isControlsOpen = !isControlsOpen} class="xl:hidden p-2 -ml-2"><Settings size={20}/></button><h1 class="text-lg xl:text-xl font-bold tracking-tighter uppercase">PolyField</h1><span class="text-[10px] opacity-50 uppercase tracking-widest hidden sm:inline-block">Harmonic Performance</span></div><div class="flex items-center gap-3 xl:gap-4 text-sm"><div class="flex items-center gap-1.5 xl:gap-2"><Volume2 size={14}/><span class="uppercase text-[10px] xl:text-xs">Audio</span></div><div class="flex items-center gap-1.5 xl:gap-2"><div class={`w-1.5 h-1.5 lg:w-2 lg:h-2 rounded-full ${midiOutputs.length > 0 ? 'bg-[#00FF00]' : 'bg-red-500'}`}></div><span class="uppercase text-[10px] xl:text-xs">MIDI</span></div></div></header>
<main class="flex-1 flex overflow-hidden relative">
{#if (isControlsOpen || isDesktopLayout) && !isSurfaceFullscreen}
<aside class="fixed inset-y-0 left-0 z-40 w-80 bg-[#E4E3E0] border-r border-[#141414] flex flex-col xl:static xl:z-0 xl:block"><div class="p-4 xl:hidden border-b border-[#141414] flex justify-between items-center bg-[#D4D3D0]"><span class="text-xs font-bold uppercase tracking-widest">Settings</span><button on:click={() => isControlsOpen = false}><X size={20}/></button></div><div class="flex-1 overflow-y-auto overscroll-contain [touch-action:pan-y] [-webkit-overflow-scrolling:touch] p-6 space-y-8 pb-24 xl:pb-8">
<section class="space-y-4"><h2 class="text-xs font-bold uppercase tracking-widest border-b border-[#141414] pb-2">Harmony</h2><select class="w-full bg-transparent border border-[#141414] p-2 text-sm uppercase" bind:value={state.scale}>{#each Object.keys(SCALES) as s}<option value={s}>{s}</option>{/each}</select><select class="w-full bg-transparent border border-[#141414] p-2 text-sm uppercase" bind:value={state.rootNote}><option value={36}>C2 (36)</option><option value={48}>C3 (48)</option><option value={60}>C4 (60)</option></select></section>
<section class="space-y-4"><h2 class="text-xs font-bold uppercase tracking-widest border-b border-[#141414] pb-2">Voices</h2><div class="grid grid-cols-2 gap-4">{#each [0,1,2,3] as i}<div class="space-y-2"><button class={`w-full p-2 text-xs uppercase border border-[#141414] ${state.voicesActive[i] ? 'bg-[#141414] text-[#E4E3E0]' : 'bg-transparent'}`} on:click={() => { const v=[...state.voicesActive] as [boolean,boolean,boolean,boolean]; v[i]=!v[i]; state={...state, voicesActive:v}; }}>V{i+1}</button><div class="flex items-center justify-between text-[10px]"><span class="opacity-50">INT</span><input type="number" class="w-10 bg-transparent border-b border-[#141414] text-right focus:outline-none" value={state.intervals[i]} on:change={(e) => { const ints=[...state.intervals] as [number,number,number,number]; ints[i]=parseInt((e.currentTarget as HTMLInputElement).value)||0; state={...state, intervals:ints}; }} /></div></div>{/each}</div></section>
<section class="space-y-4"><h2 class="text-xs font-bold uppercase tracking-widest border-b border-[#141414] pb-2">Internal Synth</h2><div class="flex gap-1">{#each ['sine','square','sawtooth','triangle'] as wf}<button class={`flex-1 p-1.5 text-[9px] uppercase border border-[#141414] ${state.waveform===wf?'bg-[#141414] text-[#E4E3E0]':''}`} on:click={() => state={...state, waveform:wf as Waveform}}>{wf.slice(0,3)}</button>{/each}</div><div class="space-y-2"><div class="flex justify-between items-center"><label class="text-xs uppercase opacity-70">Delay</label><button class={`px-3 py-1 text-[10px] uppercase border border-[#141414] ${state.delayEnabled ? 'bg-[#141414] text-[#E4E3E0]' : ''}`} on:click={() => state={...state, delayEnabled:!state.delayEnabled}}>{state.delayEnabled ? 'ON' : 'OFF'}</button></div>{#if state.delayEnabled}<div class="flex items-center gap-2"><span class="text-[10px] opacity-50 uppercase">Mix</span><input type="range" min="0" max="1" step="0.01" class="flex-1 accent-[#141414]" bind:value={state.delayMix} /><span class="text-[10px] opacity-50 w-8 text-right">{Math.round(state.delayMix*100)}%</span></div>{/if}</div></section>
<section class="space-y-4"><h2 class="text-xs font-bold uppercase tracking-widest border-b border-[#141414] pb-2">MIDI Out</h2><select class="w-full bg-transparent border border-[#141414] p-2 text-sm uppercase" bind:value={selectedMidiOut}><option value="">None</option>{#each midiOutputs as out}<option value={out.id}>{out.name}</option>{/each}</select><div class="flex gap-4"><div class="flex-1"><label class="text-xs uppercase opacity-70">Ch</label><select class="w-full bg-transparent border border-[#141414] p-2 text-sm uppercase" bind:value={state.midiChannel} disabled={state.mpeEnabled}>{#each Array.from({length:16}) as _,i}<option value={i+1}>{i+1}</option>{/each}</select></div><div class="flex-1"><label class="text-xs uppercase opacity-70">MPE</label><button class={`w-full p-2 text-sm uppercase border border-[#141414] ${state.mpeEnabled ? 'bg-[#141414] text-[#E4E3E0]' : ''}`} on:click={() => state={...state,mpeEnabled:!state.mpeEnabled}}>{state.mpeEnabled ? 'ON' : 'OFF'}</button></div></div></section>
<section class="space-y-4"><h2 class="text-xs font-bold uppercase tracking-widest border-b border-[#141414] pb-2">Motion</h2><div class="space-y-2"><label class="text-xs uppercase opacity-70">Touch Mode</label><div class="flex gap-2"><button class={`flex-1 p-2 text-xs uppercase border border-[#141414] ${state.touchMode==='mono'?'bg-[#141414] text-[#E4E3E0]':''}`} on:click={() => state={...state,touchMode:'mono'}}>Mono</button><button class={`flex-1 p-2 text-xs uppercase border border-[#141414] ${state.touchMode==='poly'?'bg-[#141414] text-[#E4E3E0]':''}`} on:click={() => state={...state,touchMode:'poly'}}>Poly</button></div></div><div class="space-y-2"><label class="text-xs uppercase opacity-70">Play Mode</label><div class="flex gap-2"><button class={`flex-1 p-2 text-xs uppercase border border-[#141414] ${state.motionMode==='free'?'bg-[#141414] text-[#E4E3E0]':''}`} on:click={() => state={...state,motionMode:'free'}}>Free</button><button class={`flex-1 p-2 text-xs uppercase border border-[#141414] ${state.motionMode==='arp'?'bg-[#141414] text-[#E4E3E0]':''}`} on:click={() => state={...state,motionMode:'arp'}}>Arp</button></div></div><div class="flex gap-1"><button class={`flex-1 p-1.5 text-[9px] uppercase border border-[#141414] ${state.clockSource==='internal'?'bg-[#141414] text-[#E4E3E0]':''}`} on:click={() => state={...state,clockSource:'internal'}}>INT</button><button class={`flex-1 p-1.5 text-[9px] uppercase border border-[#141414] ${state.clockSource==='external'?'bg-[#141414] text-[#E4E3E0]':''}`} on:click={() => state={...state,clockSource:'external'}}>EXT</button></div>{#if state.clockSource==='internal'}<div class="flex items-center justify-between text-xs"><span class="opacity-70 uppercase">BPM</span><input type="number" class="w-12 bg-transparent border-b border-[#141414] text-right focus:outline-none" value={state.bpm} min="30" max="300" on:change={(e) => state={...state,bpm:parseInt((e.currentTarget as HTMLInputElement).value)||120}} /></div>{/if}</section>
<section class="space-y-4"><h2 class="text-xs font-bold uppercase tracking-widest border-b border-[#141414] pb-2">Presets</h2><div class="flex gap-2"><button class="flex-1 p-2 text-xs uppercase border border-[#141414] flex items-center justify-center gap-2" on:click={() => localStorage.setItem('polyfield_preset',JSON.stringify(state))}><Save size={14}/> Save</button><button class="flex-1 p-2 text-xs uppercase border border-[#141414] flex items-center justify-center gap-2" on:click={() => { const s=localStorage.getItem('polyfield_preset'); if(s) state=JSON.parse(s); }}><Download size={14}/> Load</button></div></section>
</div></aside>{/if}
{#if isControlsOpen}<button class="fixed inset-0 bg-black/40 z-30 xl:hidden" on:click={() => isControlsOpen=false} aria-label="Close settings backdrop"></button>{/if}
<div class="flex-1 relative bg-[#141414] touch-none overflow-hidden p-2 xl:p-8 flex items-center justify-center"><div bind:this={surfaceRef} role="application" aria-label="Polyfield touch surface" class="w-full h-full relative cursor-crosshair border border-[#333] bg-[#1A1A1A] shadow-2xl rounded-sm overflow-hidden select-none [-webkit-user-select:none] [-webkit-touch-callout:none]" on:pointerdown={pointerDown} on:pointermove={pointerMove} on:pointerup={pointerUp} on:pointercancel={pointerUp} on:pointerleave={pointerUp}>{#each Array.from({length: state.gridSteps}) as _, i}<div class="absolute left-0 right-0 h-px bg-white/10" style={`top:${(i/state.gridSteps)*100}%`}></div><div class="absolute top-0 bottom-0 w-px bg-white/10" style={`left:${(i/state.gridSteps)*100}%`}></div>{/each}{#each Object.entries(pointers) as [id,p]}<div class="absolute top-0 bottom-0 bg-[#F27D26]/20 border-x border-[#F27D26]/40" style={`left:${(Math.floor(p.x*state.gridSteps)/state.gridSteps)*100}%;width:${(1/state.gridSteps)*100}%`}></div><div class="absolute left-0 right-0 bg-[#00FF00]/20 border-y border-[#00FF00]/40" style={`top:${(Math.floor(p.y*state.gridSteps)/state.gridSteps)*100}%;height:${(1/state.gridSteps)*100}%`}></div><div class="absolute w-6 h-6 xl:w-4 xl:h-4 border-2 border-white rounded-full -translate-x-1/2 -translate-y-1/2" style={`left:${p.x*100}%;top:${p.y*100}%`}></div>{/each}<div class="absolute bottom-3 left-3 xl:bottom-4 xl:left-4 pointer-events-none flex flex-wrap gap-1.5 xl:gap-2 max-w-[80%]">{#each Array.from(activeNotes).sort((a,b)=>a-b) as note}<div class="px-1.5 py-0.5 xl:px-2 xl:py-1 bg-white/10 text-white text-[9px] xl:text-xs rounded border border-white/20">{note}</div>{/each}</div>{#if !Object.keys(pointers).length}<div class="absolute inset-0 flex items-center justify-center pointer-events-none"><p class="text-[#E4E3E0]/20 uppercase tracking-[0.2em] text-[10px] xl:text-sm">Touch to play</p></div>{/if}{#if !isControlsOpen && !isSurfaceFullscreen}<button on:click|stopPropagation={() => isControlsOpen=true} class="xl:hidden absolute top-4 left-4 p-2 bg-white/5 border border-white/10 rounded-full text-white/50"><ChevronRight size={20}/></button>{/if}<button on:click|stopPropagation={toggleSurfaceFullscreen} class="absolute top-4 right-4 p-2 bg-white/5 border border-white/10 rounded-full text-white/70" aria-label={isSurfaceFullscreen ? 'Exit fullscreen' : 'Enter fullscreen'}>{#if isSurfaceFullscreen}<Minimize2 size={18}/>{:else}<Maximize2 size={18}/>{/if}</button></div></div>
</main></div>
